services:
  utakata_all_rust_webapp_devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    image: utakata_all_rust_webapp_devcontainer_image
    container_name: utakata_all_rust_webapp_devcontainer_container
    volumes:
      - ../workspace:/workspace
    working_dir: /workspace
    tty: true
    user: utakata
